version: 1.0.{build}
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  publish_core_console: true
  verbosity: minimal
notifications:
- provider: Webhook
  url: https://discordapp.com/api/webhooks/491321918259986452/2Nh00ywiOq1Vv7qeQNDldtMhIvNPt0TpphRfAXmyx4g8kxe6vbpLo7q8v5dxmReoFbW_
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
