version: 1.0.{build}
image: Visual Studio 2017
environment:
  WEBHOOK_URL:
    secure: iGW1I2Gs3o0hzHyPPRhbvnbfhMY1qIjcCMVUeBguWgAj3Dd7hKO3doEj8Q07J8e0doAPBCJUBwlUbt0ECxyLN+fMK5VYU3RxS6vgh66hisQkdgVSegWM76pfzV3mE32BNewsJlW6ngxOZ2GIaRWUOetw/HWWbBIDOE5CEMAJoTg=
build:
  project: GDEdit/GDEdit.sln
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  publish_core_console: true
  parallel: true
  verbosity: minimal
notifications:
- provider: Webhook
  url: https://discordapp.com/api/webhooks/491321918259986452/2Nh00ywiOq1Vv7qeQNDldtMhIvNPt0TpphRfAXmyx4g8kxe6vbpLo7q8v5dxmReoFbW_/github
  method: POST
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
